# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20170226_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 26, 2, 6, 7, 725076), verbose_name='Time completed'),
        ),
    ]
